# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2022 Satyam Bhardwaj <sabhardw@redhat.com>
# SPDX-FileCopyrightText: 2022 Utkarsh Chaurasia <uchauras@redhat.com>
# SPDX-FileCopyrightText: 2022 Avinal Kumar <avinkuma@redhat.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.apiVersion: apps/v1

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mks-ui
  namespace: mks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mks-ui
  template:
    metadata:
      labels:
        app: mks-ui
    spec:
      serviceAccountName: mks-server-sa
      containers:
      - name: mks-ui
        image: ghcr.io/miniteks/mks-ui:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        command:  [ "/app/mks-ui"]
        args:
          - -dbAddr=1.2.4.119:6379
          - -addr=:5000